# Generated by Django 3.0.4 on 2020-03-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='File',
        ),
    ]
